
name: Run OK Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb           google-chrome-stable chromium-chromedriver
        # Устанавливаем chromedriver для совместимости с текущим Chrome
        CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d $HOME/.chromedriver
        sudo mv $HOME/.chromedriver/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        google-chrome --version
        chromedriver --version

    - name: Verify Chrome & Chromedriver
      run: |
        google-chrome --version
        chromedriver --version

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run bot
      env:
        OK_EMAIL: ${{ secrets.OK_EMAIL }}
        OK_PASSWORD: ${{ secrets.OK_PASSWORD }}
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99
        python bot.py

    - name: Upload bot log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bot-log
        path: bot.log
